services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Lz67x9!A9X
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    networks:
      - opensearch-net
    depends_on:
      - opensearch

  embedding-api:
    build: ./embedding-api
    ports:
      - "8000:8000"
    networks:
      - opensearch-net
    restart: unless-stopped

  # litellm:
  #   image: ghcr.io/berriai/litellm:main
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - opensearch-net
  #   volumes:
  #     - ./litellm-config.yaml:/app/config.yaml
  #   environment:
  #     - LITELLM_CONFIG_PATH=/app/config.yaml
  #     - AZURE_OPENAI_API_KEY=dummy
  #   depends_on:
  #     - embedding-api

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge
